services:
  backend:
    image: fosskkw/url-shortener-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  frontend:
    image: fosskkw/url-shortener-frontend
    ports:
      - "5173:5173"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"